### ISSUE TITLE
Chromecast not working

### ISSUE THREAD

**Issue by Mangoxd** [Fenny/Castjs#11]
Hello , in the page it works, i mean on chrome , firefox , etc , but i made a application with android studio to show the exactly page with webview but i dont get it working , button disabled , why is that?

**Comment by Fenny** [comment]
Hi @Mangoxd ,

Did you include the Sender SDK?

```javascript
<script src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></script>
<script src="https://cdn.jsdelivr.net/gh/fenny/castjs@3.0.1/cast.min.js"></script>
```

**Comment by arnegolemar** [comment]
Hello Mr. @Mangoxd good day , do you managed to make it work by adding the scripts?
