### ISSUE TITLE
"Mute" in demo causing unexpected behaviour

### ISSUE THREAD

**Issue by ToishY** [Fenny/Castjs#12]
So I've used the demo as a basis to use for my video player, but I noticed when using the "mute" function, it completely stops audio from being played, even after trying to "unmute" it. Every other piece of media I try to cast after this lacks audio, and the only way I found out to "make the audio work again" is just by turning the television off/on.

While the documentation seems correct, you did something slightly different in the demo, which is probably the reason for this behaviour.

```
...
    if ($('#mute').hasClass('fa-volume-up')) {
      cc.mute(true);
      $('#mute').removeClass('fa-volume-up').addClass('fa-volume-mute')
    } else {
      cc.mute(false);
      $('#mute').removeClass('fa-volume-mute').addClass('fa-volume-up')
    }
...
```

By replacing the `cc.mute(true)` and `cc.mute(false)` by `cc.mute()` and `cc.unmute()` resp. it seemed to work for me.

**Comment by Fenny** [comment]
@ToishY 

Nice catch, I will fix it later today.

Thanks for your feedback!
