### ISSUE TITLE
When i pass my receiver ID, it is applied to joinpolicy

### ISSUE THREAD

**Issue by GertTimmerman** [Fenny/Castjs#13]
Hi, first of all thanks for this package, its easy to setup.

I have created my own SMR and have my own receiver ID i want to use. When i pass this ID, it is applied to the joinpolicy variable in stead of the receiver variable.

Here my code:

`this.castDevice = new Castjs('*********');`

When i output the `this.castDevice` in the console, i get this:

```javascript
castDevice: {
  availabe: true,
  controller: Object,
  description: null,
  duration: 0,
  durationPretty: "00:00:00",
  events: Object,
  joinpolicy: "*********",
  muted: false,
  paused: false,
  player: Object,
  poster: null,
  progress: 0,
  receiver: "CC1AD845",
  session: null,
  source: null,
  state: "disconnected",
  subtitles: Array[0],
  time: 0,
  timePretty: "00:00:00",
  title: null,
  volumeLevel: 1
}
```

**Comment by Fenny** [comment]
This mus be a bug in https://github.com/Fenny/Castjs/blob/master/cast.js#L10
I will take a look when I get home.

**Comment by GertTimmerman** [comment]
Any update on this?

**Comment by Fenny** [comment]
@GertTimmerman I'm so sorry, but I'm so busy atm. I can accept any PR request if you could fix it.

**Comment by peabnuts123** [comment]
I have created a PR that will fix this issue
